# Generated by Django 2.0.7 on 2018-07-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localevent',
            name='external_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='hidden',
            field=models.BooleanField(help_text='if this is selected the event will not be shown on the public site'),
        ),
    ]
