# Generated by Django 2.0.7 on 2018-07-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180715_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localevent',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
